name: Update Time Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write

jobs:
  update_time_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Update time.json file
        run: |
          # MUDANÇA: Usando a API alternativa 'timeapi.io' para evitar o erro de SSL
          API_RESPONSE=$(curl -s https://timeapi.io/api/Time/current/zone?timeZone=Etc/UTC)
          
          # Ajuste para extrair os dados da nova API
          ISO_DATETIME=$(echo $API_RESPONSE | jq -r .dateTime)
          # A nova API não fornece 'unixtime', então vamos gerá-lo a partir da data ISO
          UNIX_TIME=$(date -d "$ISO_DATETIME" +%s)
          
          # Cria o novo arquivo time.json com ambos os formatos
          echo "{\"dateTime\": \"$ISO_DATETIME\", \"unixtime\": $UNIX_TIME}" > time.json
          
          echo "Arquivo time.json foi atualizado com sucesso pela nova API."

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(bot): update time.json'
          file_pattern: 'time.json'
