name: Update Time Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write

jobs:
  update_time_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Update time.json file
        run: |
          # Adicionado --tlsv1.2 para forçar uma versão de segurança compatível e evitar o erro 35
          API_RESPONSE=$(curl -s --tlsv1.2 https://worldtimeapi.org/api/timezone/Etc/UTC)
          
          ISO_DATETIME=$(echo $API_RESPONSE | jq -r .utc_datetime)
          UNIX_TIME=$(echo $API_RESPONSE | jq -r .unixtime)
          
          echo "{\"dateTime\": \"$ISO_DATETIME\", \"unixtime\": $UNIX_TIME}" > time.json
          
          echo "Arquivo time.json foi atualizado com sucesso."

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(bot): update time.json'
          file_pattern: 'time.json'
