name: Update Time Data

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_time_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Update time.json
        run: |
          # Busca a resposta completa da API
          API_RESPONSE=$(curl -s https://worldtimeapi.org/api/timezone/Etc/UTC)
          
          # Extrai os dois valores que precisamos
          ISO_DATETIME=$(echo $API_RESPONSE | jq -r .utc_datetime)
          UNIX_TIME=$(echo $API_RESPONSE | jq -r .unixtime)
          
          # Cria o novo arquivo time.json com ambos os formatos
          echo "{\"dateTime\": \"$ISO_DATETIME\", \"unixtime\": $UNIX_TIME}" > time.json

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update time.json'
          file_pattern: 'time.json'
